//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerRess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CareerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CareerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("web.Resources.Views.Career.CareerStrings", typeof(CareerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklamalar.
        /// </summary>
        public static string acikalamalar {
            get {
                return ResourceManager.GetString("acikalamalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklamalar:.
        /// </summary>
        public static string aciklama {
            get {
                return ResourceManager.GetString("aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad:.
        /// </summary>
        public static string ad {
            get {
                return ResourceManager.GetString("ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres:.
        /// </summary>
        public static string adres {
            get {
                return ResourceManager.GetString("adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ağustos.
        /// </summary>
        public static string agustos {
            get {
                return ResourceManager.GetString("agustos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almanca.
        /// </summary>
        public static string almanca {
            get {
                return ResourceManager.GetString("almanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başvuru Formu.
        /// </summary>
        public static string applicationform {
            get {
                return ResourceManager.GetString("applicationform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başvurunuz şuan alınamıyor. Lütfen bizimle iletişime geçiniz..
        /// </summary>
        public static string applicationnotsent {
            get {
                return ResourceManager.GetString("applicationnotsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başvurunuz başarıyla alınmışır..
        /// </summary>
        public static string applicationsent {
            get {
                return ResourceManager.GetString("applicationsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aralık.
        /// </summary>
        public static string aralik {
            get {
                return ResourceManager.GetString("aralik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Askerlik Durumu.
        /// </summary>
        public static string askerlik {
            get {
                return ResourceManager.GetString("askerlik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayrılma Nedeni:.
        /// </summary>
        public static string ayrilmanedeni {
            get {
                return ResourceManager.GetString("ayrilmanedeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az.
        /// </summary>
        public static string az {
            get {
                return ResourceManager.GetString("az", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yılı.
        /// </summary>
        public static string baslangictarihi {
            get {
                return ResourceManager.GetString("baslangictarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAŞVUR.
        /// </summary>
        public static string basvur {
            get {
                return ResourceManager.GetString("basvur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekar.
        /// </summary>
        public static string bekar {
            get {
                return ResourceManager.GetString("bekar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilmiyorum.
        /// </summary>
        public static string bilmiyorum {
            get {
                return ResourceManager.GetString("bilmiyorum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Yeri.
        /// </summary>
        public static string birthcity {
            get {
                return ResourceManager.GetString("birthcity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi.
        /// </summary>
        public static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayrılış Tarihi.
        /// </summary>
        public static string bitistarihi {
            get {
                return ResourceManager.GetString("bitistarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm.
        /// </summary>
        public static string bolum {
            get {
                return ResourceManager.GetString("bolum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KARİYER.
        /// </summary>
        public static string career {
            get {
                return ResourceManager.GetString("career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep Telefonu.
        /// </summary>
        public static string ceptel {
            get {
                return ResourceManager.GetString("ceptel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet:.
        /// </summary>
        public static string cinsiyet {
            get {
                return ResourceManager.GetString("cinsiyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çok İyi.
        /// </summary>
        public static string cokiyi {
            get {
                return ResourceManager.GetString("cokiyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV&apos;niz gönderilememektedir. Lütfen iletişime geçiniz..
        /// </summary>
        public static string cv_not_sended {
            get {
                return ResourceManager.GetString("cv_not_sended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV&apos;niz başarı ile gönderilmiştir..
        /// </summary>
        public static string cv_sended {
            get {
                return ResourceManager.GetString("cv_sended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gayrimenkul Danışmanı.
        /// </summary>
        public static string danisman {
            get {
                return ResourceManager.GetString("danisman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Deneyimleri.
        /// </summary>
        public static string deneyim {
            get {
                return ResourceManager.GetString("deneyim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başvuracağınız Pozisyon.
        /// </summary>
        public static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer.
        /// </summary>
        public static string diger {
            get {
                return ResourceManager.GetString("diger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string dil {
            get {
                return ResourceManager.GetString("dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seviyesi (1-5; 1 çok az; 5 mükemmel).
        /// </summary>
        public static string dilseviye {
            get {
                return ResourceManager.GetString("dilseviye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi.
        /// </summary>
        public static string dogumtarihi {
            get {
                return ResourceManager.GetString("dogumtarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktora.
        /// </summary>
        public static string doktora {
            get {
                return ResourceManager.GetString("doktora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seviye.
        /// </summary>
        public static string egitimdurumu {
            get {
                return ResourceManager.GetString("egitimdurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ehliyet:.
        /// </summary>
        public static string ehliyet {
            get {
                return ResourceManager.GetString("ehliyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ehliyet Aldığınız Sene:.
        /// </summary>
        public static string ehliyetsene {
            get {
                return ResourceManager.GetString("ehliyetsene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ehliyet Sınıfı:.
        /// </summary>
        public static string ehliyetsinifi {
            get {
                return ResourceManager.GetString("ehliyetsinifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekim.
        /// </summary>
        public static string ekim {
            get {
                return ResourceManager.GetString("ekim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eklemek İstedikleriniz:.
        /// </summary>
        public static string eklemekistediginiz {
            get {
                return ResourceManager.GetString("eklemekistediginiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta:.
        /// </summary>
        public static string eposta {
            get {
                return ResourceManager.GetString("eposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erkek.
        /// </summary>
        public static string erkek {
            get {
                return ResourceManager.GetString("erkek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evli.
        /// </summary>
        public static string evli {
            get {
                return ResourceManager.GetString("evli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev Telefonu:.
        /// </summary>
        public static string evtel {
            get {
                return ResourceManager.GetString("evtel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eylül.
        /// </summary>
        public static string eylul {
            get {
                return ResourceManager.GetString("eylul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV göndermek için.
        /// </summary>
        public static string forsendcv {
            get {
                return ResourceManager.GetString("forsendcv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fransızca.
        /// </summary>
        public static string fransizce {
            get {
                return ResourceManager.GetString("fransizce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görev.
        /// </summary>
        public static string gorev {
            get {
                return ResourceManager.GetString("gorev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haziran.
        /// </summary>
        public static string haziran {
            get {
                return ResourceManager.GetString("haziran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri.
        /// </summary>
        public static string iletisim {
            get {
                return ResourceManager.GetString("iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Uzmanı.
        /// </summary>
        public static string iletisimuzmani {
            get {
                return ResourceManager.GetString("iletisimuzmani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlköğretim.
        /// </summary>
        public static string ilkogretim {
            get {
                return ResourceManager.GetString("ilkogretim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        public static string ingilizce {
            get {
                return ResourceManager.GetString("ingilizce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim:.
        /// </summary>
        public static string isim {
            get {
                return ResourceManager.GetString("isim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Telefonu.
        /// </summary>
        public static string istel {
            get {
                return ResourceManager.GetString("istel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İyi.
        /// </summary>
        public static string iyi {
            get {
                return ResourceManager.GetString("iyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize Katılın.
        /// </summary>
        public static string joinus {
            get {
                return ResourceManager.GetString("joinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kadın.
        /// </summary>
        public static string kain {
            get {
                return ResourceManager.GetString("kain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasım.
        /// </summary>
        public static string kasim {
            get {
                return ResourceManager.GetString("kasim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.C. Kimlik No.
        /// </summary>
        public static string kimlikno {
            get {
                return ResourceManager.GetString("kimlikno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kişisel Bilgiler.
        /// </summary>
        public static string kisisel {
            get {
                return ResourceManager.GetString("kisisel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurum.
        /// </summary>
        public static string kurum {
            get {
                return ResourceManager.GetString("kurum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaşadığı Şehir.
        /// </summary>
        public static string livingcity {
            get {
                return ResourceManager.GetString("livingcity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mart.
        /// </summary>
        public static string mart {
            get {
                return ResourceManager.GetString("mart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayıs.
        /// </summary>
        public static string mayis {
            get {
                return ResourceManager.GetString("mayis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medeni Durum.
        /// </summary>
        public static string medenidurum {
            get {
                return ResourceManager.GetString("medenidurum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mezuniyet Yılı.
        /// </summary>
        public static string mezuniyetyili {
            get {
                return ResourceManager.GetString("mezuniyetyili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil Telefon.
        /// </summary>
        public static string mobil {
            get {
                return ResourceManager.GetString("mobil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muaf.
        /// </summary>
        public static string muaf {
            get {
                return ResourceManager.GetString("muaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        public static string namesurname {
            get {
                return ResourceManager.GetString("namesurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİR SONRAKİ ADIM.
        /// </summary>
        public static string nextstep {
            get {
                return ResourceManager.GetString("nextstep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nisan.
        /// </summary>
        public static string nisan {
            get {
                return ResourceManager.GetString("nisan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notunuz.
        /// </summary>
        public static string not {
            get {
                return ResourceManager.GetString("not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocak.
        /// </summary>
        public static string ocak {
            get {
                return ResourceManager.GetString("ocak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofis Asistanı.
        /// </summary>
        public static string ofisasistani {
            get {
                return ResourceManager.GetString("ofisasistani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenildiği Yer.
        /// </summary>
        public static string ogreildigiyer {
            get {
                return ResourceManager.GetString("ogreildigiyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci.
        /// </summary>
        public static string ogrenci {
            get {
                return ResourceManager.GetString("ogrenci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenim Durumu.
        /// </summary>
        public static string ogrenimdurumu {
            get {
                return ResourceManager.GetString("ogrenimdurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ortaöğretim.
        /// </summary>
        public static string okul {
            get {
                return ResourceManager.GetString("okul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veya aşağıdaki ilgili alanlara CV bilgilerinizi yazabilirsiniz..
        /// </summary>
        public static string orclick {
            get {
                return ResourceManager.GetString("orclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orta.
        /// </summary>
        public static string orta {
            get {
                return ResourceManager.GetString("orta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrtaÖğretim Mezunu.
        /// </summary>
        public static string ortaogretim {
            get {
                return ResourceManager.GetString("ortaogretim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozisyon.
        /// </summary>
        public static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozisyonlar( seçiniz).
        /// </summary>
        public static string positions {
            get {
                return ResourceManager.GetString("positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referanslar.
        /// </summary>
        public static string referans {
            get {
                return ResourceManager.GetString("referans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabit Telefon:.
        /// </summary>
        public static string sabittel {
            get {
                return ResourceManager.GetString("sabittel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şöför.
        /// </summary>
        public static string sofor {
            get {
                return ResourceManager.GetString("sofor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad:.
        /// </summary>
        public static string soyad {
            get {
                return ResourceManager.GetString("soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şubat.
        /// </summary>
        public static string subat {
            get {
                return ResourceManager.GetString("subat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC No.
        /// </summary>
        public static string tcno {
            get {
                return ResourceManager.GetString("tcno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temmuz.
        /// </summary>
        public static string temmuz {
            get {
                return ResourceManager.GetString("temmuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üniversite-Lisans.
        /// </summary>
        public static string universite {
            get {
                return ResourceManager.GetString("universite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Var.
        /// </summary>
        public static string var {
            get {
                return ResourceManager.GetString("var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizimle çalışmak isterseniz CV’nizi bırakabilirsiniz..
        /// </summary>
        public static string workwithus {
            get {
                return ResourceManager.GetString("workwithus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yabancı Dil Bilgisi.
        /// </summary>
        public static string yabancidil {
            get {
                return ResourceManager.GetString("yabancidil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yabancı Dil Bilgisi:.
        /// </summary>
        public static string yabancidilbilgisi {
            get {
                return ResourceManager.GetString("yabancidilbilgisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapıldı.
        /// </summary>
        public static string yapildi {
            get {
                return ResourceManager.GetString("yapildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılmadı.
        /// </summary>
        public static string yapilmadi {
            get {
                return ResourceManager.GetString("yapilmadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yok.
        /// </summary>
        public static string yok {
            get {
                return ResourceManager.GetString("yok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üniversite-Master ve diğer.
        /// </summary>
        public static string yukseklisans {
            get {
                return ResourceManager.GetString("yukseklisans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lise.
        /// </summary>
        public static string yuksekokul {
            get {
                return ResourceManager.GetString("yuksekokul", resourceCulture);
            }
        }
    }
}
