//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Briefs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Brief {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Brief() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("web.Resources.Views.Brief.Brief", typeof(Brief).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız Soyadınız.
        /// </summary>
        public static string adsoyad {
            get {
                return ResourceManager.GetString("adsoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha detaylı arama kaydı oluşturmak için tıklayınız.
        /// </summary>
        public static string detailsearch {
            get {
                return ResourceManager.GetString("detailsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha detaylı brifing / mesaj kaydı oluşturmak için tıklayınız.
        /// </summary>
        public static string detay {
            get {
                return ResourceManager.GetString("detay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta Adresiniz.
        /// </summary>
        public static string eposta {
            get {
                return ResourceManager.GetString("eposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev.
        /// </summary>
        public static string evtel {
            get {
                return ResourceManager.GetString("evtel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gsm.
        /// </summary>
        public static string gsm {
            get {
                return ResourceManager.GetString("gsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESAJ BIRAKIN SİZİ ARAYALIM.
        /// </summary>
        public static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş.
        /// </summary>
        public static string istel {
            get {
                return ResourceManager.GetString("istel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize Mesajınız.
        /// </summary>
        public static string mesaj {
            get {
                return ResourceManager.GetString("mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Numaralarınız.
        /// </summary>
        public static string tels {
            get {
                return ResourceManager.GetString("tels", resourceCulture);
            }
        }
    }
}
