//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BriefDetails {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Detail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Detail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("web.Resources.Views.Brief.Detail", typeof(Detail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad, Soyad :.
        /// </summary>
        public static string adsoyad {
            get {
                return ResourceManager.GetString("adsoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başka varsa belirtiniz:.
        /// </summary>
        public static string baska {
            get {
                return ResourceManager.GetString("baska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binadaki Kat Sayısı.
        /// </summary>
        public static string binadakikatsayisi {
            get {
                return ResourceManager.GetString("binadakikatsayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binanın Yaşı.
        /// </summary>
        public static string binayasi {
            get {
                return ResourceManager.GetString("binayasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulunduğu Kat.
        /// </summary>
        public static string bulndugukat {
            get {
                return ResourceManager.GetString("bulndugukat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depozito.
        /// </summary>
        public static string depozito {
            get {
                return ResourceManager.GetString("depozito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devren ise lütfen detayları belirtiniz.
        /// </summary>
        public static string devrendetay {
            get {
                return ResourceManager.GetString("devrendetay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail :.
        /// </summary>
        public static string emil {
            get {
                return ResourceManager.GetString("emil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat Aralığı ( max ve min değeri para birimi ile belirtiniz).
        /// </summary>
        public static string fiytaraligi {
            get {
                return ResourceManager.GetString("fiytaraligi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getiri beklentiniz (tl, usd, aylık, yıllık ).
        /// </summary>
        public static string getiribeklentiniz {
            get {
                return ResourceManager.GetString("getiribeklentiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAYLI MESAJ FORMU.
        /// </summary>
        public static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gayrimenkul ile ilgili nasıl bir işlem yapmak istiyorsunuz?.
        /// </summary>
        public static string header2 {
            get {
                return ResourceManager.GetString("header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aradığınız gayrimenkulün özelliklerini yazınız.
        /// </summary>
        public static string header3 {
            get {
                return ResourceManager.GetString("header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        public static string ilce {
            get {
                return ResourceManager.GetString("ilce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isınma Tipi.
        /// </summary>
        public static string isinmatipi {
            get {
                return ResourceManager.GetString("isinmatipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b. Kiracı bulmak.
        /// </summary>
        public static string kiracibulmak {
            get {
                return ResourceManager.GetString("kiracibulmak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d. Kiralamak.
        /// </summary>
        public static string kiralamak {
            get {
                return ResourceManager.GetString("kiralamak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konut.
        /// </summary>
        public static string konut {
            get {
                return ResourceManager.GetString("konut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krediye Uygunluk.
        /// </summary>
        public static string krediyeuygunluk {
            get {
                return ResourceManager.GetString("krediyeuygunluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanım Durumu ( boş, malsahibi oturuyor vb..).
        /// </summary>
        public static string kullanimurumu {
            get {
                return ResourceManager.GetString("kullanimurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokasyon.
        /// </summary>
        public static string lokasyon {
            get {
                return ResourceManager.GetString("lokasyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahalle.
        /// </summary>
        public static string mahalle {
            get {
                return ResourceManager.GetString("mahalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2.
        /// </summary>
        public static string metrekare {
            get {
                return ResourceManager.GetString("metrekare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mülk Tipi ( Plaza, villa, depo vb..).
        /// </summary>
        public static string mulktipi {
            get {
                return ResourceManager.GetString("mulktipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm/Oda Sayısı.
        /// </summary>
        public static string odasayisi {
            get {
                return ResourceManager.GetString("odasayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c. Satınalmak.
        /// </summary>
        public static string satinalmak {
            get {
                return ResourceManager.GetString("satinalmak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.Satmak.
        /// </summary>
        public static string satmak {
            get {
                return ResourceManager.GetString("satmak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        public static string sehir {
            get {
                return ResourceManager.GetString("sehir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÖNDER.
        /// </summary>
        public static string sendbutton {
            get {
                return ResourceManager.GetString("sendbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tapu Durumu ( kat irtifakı, kat mülkiyeti).
        /// </summary>
        public static string tapudurumu {
            get {
                return ResourceManager.GetString("tapudurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string tarih {
            get {
                return ResourceManager.GetString("tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        public static string tel {
            get {
                return ResourceManager.GetString("tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticari.
        /// </summary>
        public static string ticari {
            get {
                return ResourceManager.GetString("ticari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakıt Tipi.
        /// </summary>
        public static string yakittipi {
            get {
                return ResourceManager.GetString("yakittipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapının Durumu ( sıfır, ikinci el vb..).
        /// </summary>
        public static string ypıdurumu {
            get {
                return ResourceManager.GetString("ypıdurumu", resourceCulture);
            }
        }
    }
}
