//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfferRess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OffersStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OffersStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("web.Resources.Views.Offers.OffersStrings", typeof(OffersStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen ürün sayfasından ürün ekleyiniz..
        /// </summary>
        public static string addproductmessage {
            get {
                return ResourceManager.GetString("addproductmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif listenizde hiç ürün bulunmamakta!.
        /// </summary>
        public static string emptylist {
            get {
                return ResourceManager.GetString("emptylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurum Adı.
        /// </summary>
        public static string instname {
            get {
                return ResourceManager.GetString("instname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        public static string namesurname {
            get {
                return ResourceManager.GetString("namesurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif isteğiniz alınmıştır!.
        /// </summary>
        public static string offerdeliveredmessage {
            get {
                return ResourceManager.GetString("offerdeliveredmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif Formu.
        /// </summary>
        public static string offerform {
            get {
                return ResourceManager.GetString("offerform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En kısa zamanda değerlendirilerek geri dönüş yapılacaktır..
        /// </summary>
        public static string offernotifymessage {
            get {
                return ResourceManager.GetString("offernotifymessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string tel {
            get {
                return ResourceManager.GetString("tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünvan.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazılım, donanım ve PC bağlantısı istiyorum.
        /// </summary>
        public static string wanttohardware {
            get {
                return ResourceManager.GetString("wanttohardware", resourceCulture);
            }
        }
    }
}
