//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EstateStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EstateStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("web.Resources.Views.Estate.EstateStrings", typeof(EstateStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string aciklama {
            get {
                return ResourceManager.GetString("aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aidat/Yönetim.
        /// </summary>
        public static string aidatyonetim {
            get {
                return ResourceManager.GetString("aidatyonetim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alan.
        /// </summary>
        public static string alan {
            get {
                return ResourceManager.GetString("alan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arsa.
        /// </summary>
        public static string arsa {
            get {
                return ResourceManager.GetString("arsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banyo/WC.
        /// </summary>
        public static string banyowc {
            get {
                return ResourceManager.GetString("banyowc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binadaki Kat Sayısı.
        /// </summary>
        public static string binadakikatsayisi {
            get {
                return ResourceManager.GetString("binadakikatsayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binanın Yaşı.
        /// </summary>
        public static string binaninyasi {
            get {
                return ResourceManager.GetString("binaninyasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bina Taban Alanı m2.
        /// </summary>
        public static string binatamanalani {
            get {
                return ResourceManager.GetString("binatamanalani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brüt Alan.
        /// </summary>
        public static string brutalan {
            get {
                return ResourceManager.GetString("brutalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulunduğu Arsa m2.
        /// </summary>
        public static string bulunduguarsa {
            get {
                return ResourceManager.GetString("bulunduguarsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulunduğu Kat.
        /// </summary>
        public static string bulundugukat {
            get {
                return ResourceManager.GetString("bulundugukat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cephe/Yön.
        /// </summary>
        public static string cepheyon {
            get {
                return ResourceManager.GetString("cepheyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim için tıklayın.
        /// </summary>
        public static string contactBtn {
            get {
                return ResourceManager.GetString("contactBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depozito.
        /// </summary>
        public static string depozito {
            get {
                return ResourceManager.GetString("depozito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devren.
        /// </summary>
        public static string devren {
            get {
                return ResourceManager.GetString("devren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Adresiniz*.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Adresi*.
        /// </summary>
        public static string femail {
            get {
                return ResourceManager.GetString("femail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string fiyat {
            get {
                return ResourceManager.GetString("fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        public static string fname {
            get {
                return ResourceManager.GetString("fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşınızın.
        /// </summary>
        public static string friend {
            get {
                return ResourceManager.GetString("friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadı.
        /// </summary>
        public static string fsurname {
            get {
                return ResourceManager.GetString("fsurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlan no.
        /// </summary>
        public static string ilanno {
            get {
                return ResourceManager.GetString("ilanno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isınma Tipi.
        /// </summary>
        public static string isinmatipi {
            get {
                return ResourceManager.GetString("isinmatipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşyeri.
        /// </summary>
        public static string isyeri {
            get {
                return ResourceManager.GetString("isyeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kira Getirisi.
        /// </summary>
        public static string kiragetirisi {
            get {
                return ResourceManager.GetString("kiragetirisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiralık.
        /// </summary>
        public static string kiralik {
            get {
                return ResourceManager.GetString("kiralik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konut.
        /// </summary>
        public static string konut {
            get {
                return ResourceManager.GetString("konut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krediye Uygunluk.
        /// </summary>
        public static string krediyeuygunluk {
            get {
                return ResourceManager.GetString("krediyeuygunluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanım Durumu.
        /// </summary>
        public static string kullanimdurumu {
            get {
                return ResourceManager.GetString("kullanimdurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Alan.
        /// </summary>
        public static string netalan {
            get {
                return ResourceManager.GetString("netalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm/Oda Sayısı.
        /// </summary>
        public static string oda {
            get {
                return ResourceManager.GetString("oda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otopark.
        /// </summary>
        public static string otopark {
            get {
                return ResourceManager.GetString("otopark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parakende.
        /// </summary>
        public static string parakende {
            get {
                return ResourceManager.GetString("parakende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazdırmak için tıklayın....
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satılık.
        /// </summary>
        public static string satilik {
            get {
                return ResourceManager.GetString("satilik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başka birine yollamak isterseniz tıklayın.
        /// </summary>
        public static string sendingother {
            get {
                return ResourceManager.GetString("sendingother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadınız.
        /// </summary>
        public static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takas.
        /// </summary>
        public static string takas {
            get {
                return ResourceManager.GetString("takas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tapu Durumu.
        /// </summary>
        public static string tapudurumu {
            get {
                return ResourceManager.GetString("tapudurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string tarih {
            get {
                return ResourceManager.GetString("tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşına Tavsiye Et.
        /// </summary>
        public static string tavsiyeet {
            get {
                return ResourceManager.GetString("tavsiyeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portföy Tipi.
        /// </summary>
        public static string tip {
            get {
                return ResourceManager.GetString("tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Tipi.
        /// </summary>
        public static string tipemlak {
            get {
                return ResourceManager.GetString("tipemlak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakıt Tipi.
        /// </summary>
        public static string yakittipi {
            get {
                return ResourceManager.GetString("yakittipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapının Durumu.
        /// </summary>
        public static string yapinindurumu {
            get {
                return ResourceManager.GetString("yapinindurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizin.
        /// </summary>
        public static string your {
            get {
                return ResourceManager.GetString("your", resourceCulture);
            }
        }
    }
}
