//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedRess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("web.Resources.Views.Shared.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string aboutus {
            get {
                return ResourceManager.GetString("aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue İstanbul Hakkında.
        /// </summary>
        public static string aboutusvenue {
            get {
                return ResourceManager.GetString("aboutusvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string aciklama {
            get {
                return ResourceManager.GetString("aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açık otopark.
        /// </summary>
        public static string acikotopark {
            get {
                return ResourceManager.GetString("acikotopark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Bilgileri ve Google Map.
        /// </summary>
        public static string addressandgooglemap {
            get {
                return ResourceManager.GetString("addressandgooglemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylı Arama.
        /// </summary>
        public static string advancedsearch {
            get {
                return ResourceManager.GetString("advancedsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danışmanlarımız.
        /// </summary>
        public static string advisors {
            get {
                return ResourceManager.GetString("advisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aidat/Yönetim.
        /// </summary>
        public static string aidatyonetim {
            get {
                return ResourceManager.GetString("aidatyonetim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alan.
        /// </summary>
        public static string alan {
            get {
                return ResourceManager.GetString("alan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümü.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arsa.
        /// </summary>
        public static string arsa {
            get {
                return ResourceManager.GetString("arsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Bilgileri.
        /// </summary>
        public static string bankaccounts {
            get {
                return ResourceManager.GetString("bankaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banyo/WC.
        /// </summary>
        public static string banyowc {
            get {
                return ResourceManager.GetString("banyowc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binadaki Kat Sayısı.
        /// </summary>
        public static string binadakikatsayisi {
            get {
                return ResourceManager.GetString("binadakikatsayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binanın Yaşı.
        /// </summary>
        public static string binaninyasi {
            get {
                return ResourceManager.GetString("binaninyasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje m².
        /// </summary>
        public static string binatamanalani {
            get {
                return ResourceManager.GetString("binatamanalani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka.
        /// </summary>
        public static string brand {
            get {
                return ResourceManager.GetString("brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mesajlar.
        /// </summary>
        public static string brifing {
            get {
                return ResourceManager.GetString("brifing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brüt Alan.
        /// </summary>
        public static string brutalan {
            get {
                return ResourceManager.GetString("brutalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bina Yaşı.
        /// </summary>
        public static string buildingage {
            get {
                return ResourceManager.GetString("buildingage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arsa m².
        /// </summary>
        public static string bulunduguarsa {
            get {
                return ResourceManager.GetString("bulunduguarsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulunduğu Kat.
        /// </summary>
        public static string bulundugukat {
            get {
                return ResourceManager.GetString("bulundugukat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kariyer Olanakları.
        /// </summary>
        public static string careeropportunities {
            get {
                return ResourceManager.GetString("careeropportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merkez Ofis.
        /// </summary>
        public static string centeroffice {
            get {
                return ResourceManager.GetString("centeroffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cephe/Yön.
        /// </summary>
        public static string cepheyon {
            get {
                return ResourceManager.GetString("cepheyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sertifikalarımız.
        /// </summary>
        public static string certificates {
            get {
                return ResourceManager.GetString("certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkedin profili için tıklayınız.
        /// </summary>
        public static string clickforlinkedin {
            get {
                return ResourceManager.GetString("clickforlinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portföy detayı için resimlerin üstüne tıklayınız.
        /// </summary>
        public static string clickonimages {
            get {
                return ResourceManager.GetString("clickonimages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamamlanmış Projeler.
        /// </summary>
        public static string completedprojects {
            get {
                return ResourceManager.GetString("completedprojects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim için tıklayın.
        /// </summary>
        public static string contactBtn {
            get {
                return ResourceManager.GetString("contactBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri.
        /// </summary>
        public static string contactdetails {
            get {
                return ResourceManager.GetString("contactdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Formu.
        /// </summary>
        public static string contactform {
            get {
                return ResourceManager.GetString("contactform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize Ulaşın.
        /// </summary>
        public static string contactus {
            get {
                return ResourceManager.GetString("contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm hakları saklıdır, Copyright 2014..
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string culture {
            get {
                return ResourceManager.GetString("culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string culturename {
            get {
                return ResourceManager.GetString("culturename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depozito.
        /// </summary>
        public static string depozito {
            get {
                return ResourceManager.GetString("depozito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detay.
        /// </summary>
        public static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devren.
        /// </summary>
        public static string devren {
            get {
                return ResourceManager.GetString("devren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer (Lüks konut).
        /// </summary>
        public static string digerlukskonut {
            get {
                return ResourceManager.GetString("digerlukskonut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        public static string district {
            get {
                return ResourceManager.GetString("district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÖKÜMANLAR.
        /// </summary>
        public static string documents {
            get {
                return ResourceManager.GetString("documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekipmanlarımız.
        /// </summary>
        public static string equipments {
            get {
                return ResourceManager.GetString("equipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gayrimenkul Danışmanı.
        /// </summary>
        public static string estateconsultant {
            get {
                return ResourceManager.GetString("estateconsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Tipi.
        /// </summary>
        public static string estatetype {
            get {
                return ResourceManager.GetString("estatetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzmanlık Alanlarımız.
        /// </summary>
        public static string expertise {
            get {
                return ResourceManager.GetString("expertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öne Çıkan Gayrimenkuller.
        /// </summary>
        public static string featuredproperties {
            get {
                return ResourceManager.GetString("featuredproperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Adresi*.
        /// </summary>
        public static string femail {
            get {
                return ResourceManager.GetString("femail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mülkün broşürü / sunumu için tıklayınız.
        /// </summary>
        public static string fileDown {
            get {
                return ResourceManager.GetString("fileDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmalar ve Markalar.
        /// </summary>
        public static string firmsandbrands {
            get {
                return ResourceManager.GetString("firmsandbrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string fiyat {
            get {
                return ResourceManager.GetString("fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        public static string fname {
            get {
                return ResourceManager.GetString("fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurucular ve Yönetim.
        /// </summary>
        public static string founders {
            get {
                return ResourceManager.GetString("founders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşınızın.
        /// </summary>
        public static string friend {
            get {
                return ResourceManager.GetString("friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadı.
        /// </summary>
        public static string fsurname {
            get {
                return ResourceManager.GetString("fsurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Dön.
        /// </summary>
        public static string goback {
            get {
                return ResourceManager.GetString("goback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiralık.
        /// </summary>
        public static string hired {
            get {
                return ResourceManager.GetString("hired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANASAYFA.
        /// </summary>
        public static string homepage {
            get {
                return ResourceManager.GetString("homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otel ve ağırlama sektöründe uzmanlaşmış networkümüzdeki deneyimli ekip arkadaşlarımız bu turistik işletmelerinin alım-satımına yönelik aracılık hizmetleri sunmaktadır..
        /// </summary>
        public static string hotelentertainmenttext {
            get {
                return ResourceManager.GetString("hotelentertainmenttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmamız gerek yerli gerekse yabancı müşterilerinin dünya konut sektöründeki önemi her geçen gün daha artan İstanbul’un özellikli bölgelerindeki konut kiralama, satış veya satınalma ihtiyaçlarını müşteri odaklı ve kişiye özel bir yaklaşımla profesyonel, hızlı ve güvenilir bir şekilde karşılamaktadır..
        /// </summary>
        public static string hotelluxrytext {
            get {
                return ResourceManager.GetString("hotelluxrytext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konut.
        /// </summary>
        public static string housing {
            get {
                return ResourceManager.GetString("housing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnsan Kaynakları.
        /// </summary>
        public static string humanresources {
            get {
                return ResourceManager.GetString("humanresources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlan no.
        /// </summary>
        public static string ilanno {
            get {
                return ResourceManager.GetString("ilanno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticari dünyanın realitesini çok iyi bilen tecrübeli endüstriyel ve lojistik network ekibimiz müşterilerimizin gereksinimlerini çok iyi anlayabilmekte ve kendilerine yüksek kalitede profesyonel hizmet sunabilmektedir..
        /// </summary>
        public static string industrylogistictext {
            get {
                return ResourceManager.GetString("industrylogistictext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KURUMSAL.
        /// </summary>
        public static string institutional {
            get {
                return ResourceManager.GetString("institutional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isınma Tipi.
        /// </summary>
        public static string isinmatipi {
            get {
                return ResourceManager.GetString("isinmatipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofis.
        /// </summary>
        public static string isyeri {
            get {
                return ResourceManager.GetString("isyeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşyeri/Konut.
        /// </summary>
        public static string isyerikonut {
            get {
                return ResourceManager.GetString("isyerikonut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapalı otopark.
        /// </summary>
        public static string kapaliotopark {
            get {
                return ResourceManager.GetString("kapaliotopark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kira Getirisi.
        /// </summary>
        public static string kiragetirisi {
            get {
                return ResourceManager.GetString("kiragetirisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiralık.
        /// </summary>
        public static string kiralik {
            get {
                return ResourceManager.GetString("kiralik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konut.
        /// </summary>
        public static string konut {
            get {
                return ResourceManager.GetString("konut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krediye Uygunluk.
        /// </summary>
        public static string krediyeuygunluk {
            get {
                return ResourceManager.GetString("krediyeuygunluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanım Durumu.
        /// </summary>
        public static string kullanimdurumu {
            get {
                return ResourceManager.GetString("kullanimdurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arsa.
        /// </summary>
        public static string land {
            get {
                return ResourceManager.GetString("land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network’ümüzdeki deneyimli danışmanlar müşterilerimizin ihtiyacı olan arsaları bulmada ve mevcut arsalarını değerlendirmede yüksek kalitede profesyonel hizmet sunabilmektedir..
        /// </summary>
        public static string landtext {
            get {
                return ResourceManager.GetString("landtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Bırakın, Geri Dönelim.
        /// </summary>
        public static string leaveyourbrief {
            get {
                return ResourceManager.GetString("leaveyourbrief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAĞLANTILAR.
        /// </summary>
        public static string links {
            get {
                return ResourceManager.GetString("links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt.
        /// </summary>
        public static string locality {
            get {
                return ResourceManager.GetString("locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harita.
        /// </summary>
        public static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektörden Haberler.
        /// </summary>
        public static string marketnews {
            get {
                return ResourceManager.GetString("marketnews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hakkimizda.
        /// </summary>
        public static string menu_aboutus {
            get {
                return ResourceManager.GetString("menu_aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detayli-arama.
        /// </summary>
        public static string menu_advancedsearch {
            get {
                return ResourceManager.GetString("menu_advancedsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tum-haberler.
        /// </summary>
        public static string menu_allnews {
            get {
                return ResourceManager.GetString("menu_allnews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basvuru.
        /// </summary>
        public static string menu_application {
            get {
                return ResourceManager.GetString("menu_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banka-hesaplari.
        /// </summary>
        public static string menu_bankaccounts {
            get {
                return ResourceManager.GetString("menu_bankaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kariyer.
        /// </summary>
        public static string menu_career {
            get {
                return ResourceManager.GetString("menu_career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sertifikalar.
        /// </summary>
        public static string menu_certificates {
            get {
                return ResourceManager.GetString("menu_certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tamamlanan-projeler.
        /// </summary>
        public static string menu_completedprojects {
            get {
                return ResourceManager.GetString("menu_completedprojects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iletisim-bilgileri.
        /// </summary>
        public static string menu_contactdetails {
            get {
                return ResourceManager.GetString("menu_contactdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iletisim-formu.
        /// </summary>
        public static string menu_contactform {
            get {
                return ResourceManager.GetString("menu_contactform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        public static string menu_culture {
            get {
                return ResourceManager.GetString("menu_culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dokumanlar.
        /// </summary>
        public static string menu_documents {
            get {
                return ResourceManager.GetString("menu_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ekipmanlar.
        /// </summary>
        public static string menu_equipments {
            get {
                return ResourceManager.GetString("menu_equipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anasayfa.
        /// </summary>
        public static string menu_homepage {
            get {
                return ResourceManager.GetString("menu_homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insan-kaynaklari.
        /// </summary>
        public static string menu_humanresources {
            get {
                return ResourceManager.GetString("menu_humanresources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hakkimizda.
        /// </summary>
        public static string menu_institutional {
            get {
                return ResourceManager.GetString("menu_institutional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linkler.
        /// </summary>
        public static string menu_links {
            get {
                return ResourceManager.GetString("menu_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to haberler.
        /// </summary>
        public static string menu_news {
            get {
                return ResourceManager.GetString("menu_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teklif.
        /// </summary>
        public static string menu_offer {
            get {
                return ResourceManager.GetString("menu_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devam-eden-projeler.
        /// </summary>
        public static string menu_ongoingprojects {
            get {
                return ResourceManager.GetString("menu_ongoingprojects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basinda-biz.
        /// </summary>
        public static string menu_onpress {
            get {
                return ResourceManager.GetString("menu_onpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acik-pozisyonlar.
        /// </summary>
        public static string menu_openpositions {
            get {
                return ResourceManager.GetString("menu_openpositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hizmetlerimiz.
        /// </summary>
        public static string menu_ourservices {
            get {
                return ResourceManager.GetString("menu_ourservices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ekibimiz.
        /// </summary>
        public static string menu_ourteam {
            get {
                return ResourceManager.GetString("menu_ourteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urun-detay.
        /// </summary>
        public static string menu_productdetail {
            get {
                return ResourceManager.GetString("menu_productdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urunler.
        /// </summary>
        public static string menu_products {
            get {
                return ResourceManager.GetString("menu_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projeler.
        /// </summary>
        public static string menu_projects {
            get {
                return ResourceManager.GetString("menu_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to referanslar.
        /// </summary>
        public static string menu_references {
            get {
                return ResourceManager.GetString("menu_references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detayli-arama.
        /// </summary>
        public static string menu_searchestate {
            get {
                return ResourceManager.GetString("menu_searchestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sektorler.
        /// </summary>
        public static string menu_sectors {
            get {
                return ResourceManager.GetString("menu_sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hizmetler.
        /// </summary>
        public static string menu_services {
            get {
                return ResourceManager.GetString("menu_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to siteharitasi.
        /// </summary>
        public static string menu_sitemap {
            get {
                return ResourceManager.GetString("menu_sitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cozum-ortaklari.
        /// </summary>
        public static string menu_solutionpartners {
            get {
                return ResourceManager.GetString("menu_solutionpartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vizyon-misyon.
        /// </summary>
        public static string menu_visionmision {
            get {
                return ResourceManager.GetString("menu_visionmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neden-biz.
        /// </summary>
        public static string menu_whyus {
            get {
                return ResourceManager.GetString("menu_whyus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one-cikan-gayrimenkuller.
        /// </summary>
        public static string menupopularestates {
            get {
                return ResourceManager.GetString("menupopularestates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misyonumuz.
        /// </summary>
        public static string mision {
            get {
                return ResourceManager.GetString("mision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daha fazlası....
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha büyük görüntüle.
        /// </summary>
        public static string morebig {
            get {
                return ResourceManager.GetString("morebig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif Listem.
        /// </summary>
        public static string myofferlist {
            get {
                return ResourceManager.GetString("myofferlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m².
        /// </summary>
        public static string netalan {
            get {
                return ResourceManager.GetString("netalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberler.
        /// </summary>
        public static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Detayı.
        /// </summary>
        public static string newsdetail {
            get {
                return ResourceManager.GetString("newsdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm/Oda Sayısı.
        /// </summary>
        public static string oda {
            get {
                return ResourceManager.GetString("oda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deneyimli ekip ve networkumüzle İstanbul’un her noktasında, ofis satın alma, kiralama, satış veya değerleme konularında danışmanlık hizmeti sunmaktayız..
        /// </summary>
        public static string officetext {
            get {
                return ResourceManager.GetString("officetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam Eden Projeler.
        /// </summary>
        public static string ongoingprojects {
            get {
                return ResourceManager.GetString("ongoingprojects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basında Venue İstanbul.
        /// </summary>
        public static string onpress {
            get {
                return ResourceManager.GetString("onpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açık Pozisyonlar.
        /// </summary>
        public static string openpositions {
            get {
                return ResourceManager.GetString("openpositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otel ve Ağırlama.
        /// </summary>
        public static string otelveagirlama {
            get {
                return ResourceManager.GetString("otelveagirlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer Faaliyetlerimiz.
        /// </summary>
        public static string otheroperations {
            get {
                return ResourceManager.GetString("otheroperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otopark.
        /// </summary>
        public static string otopark {
            get {
                return ResourceManager.GetString("otopark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biz.
        /// </summary>
        public static string our {
            get {
                return ResourceManager.GetString("our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşterilerimiz.
        /// </summary>
        public static string ourcustomers {
            get {
                return ResourceManager.GetString("ourcustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİZDEN HABERLER.
        /// </summary>
        public static string ournews {
            get {
                return ResourceManager.GetString("ournews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetlerimiz.
        /// </summary>
        public static string ourservices {
            get {
                return ResourceManager.GetString("ourservices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekibimiz.
        /// </summary>
        public static string ourteam {
            get {
                return ResourceManager.GetString("ourteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KONTROLMATİK.
        /// </summary>
        public static string pagetitle {
            get {
                return ResourceManager.GetString("pagetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parakende.
        /// </summary>
        public static string parakende {
            get {
                return ResourceManager.GetString("parakende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perakende.
        /// </summary>
        public static string perakende {
            get {
                return ResourceManager.GetString("perakende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofis.
        /// </summary>
        public static string plazakati {
            get {
                return ResourceManager.GetString("plazakati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaza Ofis Katı.
        /// </summary>
        public static string plazaofiskati {
            get {
                return ResourceManager.GetString("plazaofiskati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Seçiniz.
        /// </summary>
        public static string pleaseselect {
            get {
                return ResourceManager.GetString("pleaseselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öne Çıkan Gayrimenkuller.
        /// </summary>
        public static string popularestates {
            get {
                return ResourceManager.GetString("popularestates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat Aralığı.
        /// </summary>
        public static string pricerange {
            get {
                return ResourceManager.GetString("pricerange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazdırmak için tıklayın....
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kodu.
        /// </summary>
        public static string product_code {
            get {
                return ResourceManager.GetString("product_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Detayı.
        /// </summary>
        public static string projectedetail {
            get {
                return ResourceManager.GetString("projectedetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projelerimiz.
        /// </summary>
        public static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans No.
        /// </summary>
        public static string referenceno {
            get {
                return ResourceManager.GetString("referenceno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referanslar.
        /// </summary>
        public static string references {
            get {
                return ResourceManager.GetString("references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurucularımızın uzun iş hayatı boyunca hizmet verdiği firma ve markalardan bazıları.....
        /// </summary>
        public static string referencestext {
            get {
                return ResourceManager.GetString("referencestext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen gerekli alanları eksiksiz ve doğru bir şekilde doldurunuz.
        /// </summary>
        public static string requiredfields {
            get {
                return ResourceManager.GetString("requiredfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        public static string resetbtn {
            get {
                return ResourceManager.GetString("resetbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hızlı ve değişken parakende sektörünü çok iyi bilen ve bu sektörün gelişmelerini devamlı izleyen deneyimli network kadromuz İstanbul’un ana cadde ve alışveriş merkezlerindeki mal sahipleri, perakendeci ve geliştiricilerine kaliteli ve hızlı hizmet verme yetisine sahiptir..
        /// </summary>
        public static string retailtext {
            get {
                return ResourceManager.GetString("retailtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm/Oda.
        /// </summary>
        public static string roomcount {
            get {
                return ResourceManager.GetString("roomcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanayi ve Lojistik.
        /// </summary>
        public static string sanayivelojistik {
            get {
                return ResourceManager.GetString("sanayivelojistik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satılık.
        /// </summary>
        public static string satilik {
            get {
                return ResourceManager.GetString("satilik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string searchbtn {
            get {
                return ResourceManager.GetString("searchbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anahtar kelimeye göre ara.
        /// </summary>
        public static string searchbykeyword {
            get {
                return ResourceManager.GetString("searchbykeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gayrimenkul Arama.
        /// </summary>
        public static string searchestate {
            get {
                return ResourceManager.GetString("searchestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site içi arama.
        /// </summary>
        public static string searchinsite {
            get {
                return ResourceManager.GetString("searchinsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama Sonuçları.
        /// </summary>
        public static string searchresult {
            get {
                return ResourceManager.GetString("searchresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzülerek aradığınız kriterde bir kaydımız olmadığını belirtmek zorundayız.&lt;br&gt;Dilerseniz aşağıdaki formu doldurun, size en kısa sürede geri dönelim..
        /// </summary>
        public static string searchresultstring {
            get {
                return ResourceManager.GetString("searchresultstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektörler.
        /// </summary>
        public static string sectors {
            get {
                return ResourceManager.GetString("sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string send1 {
            get {
                return ResourceManager.GetString("send1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başka birine yollamak isterseniz tıklayın.
        /// </summary>
        public static string sendingother {
            get {
                return ResourceManager.GetString("sendingother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetler.
        /// </summary>
        public static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Haritası.
        /// </summary>
        public static string sitemap {
            get {
                return ResourceManager.GetString("sitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satılık.
        /// </summary>
        public static string sold {
            get {
                return ResourceManager.GetString("sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çözüm Ortaklarımız.
        /// </summary>
        public static string solutionpartners {
            get {
                return ResourceManager.GetString("solutionpartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrekare.
        /// </summary>
        public static string squaremeters {
            get {
                return ResourceManager.GetString("squaremeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadınız.
        /// </summary>
        public static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takas.
        /// </summary>
        public static string takas {
            get {
                return ResourceManager.GetString("takas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tapu Durumu.
        /// </summary>
        public static string tapudurumu {
            get {
                return ResourceManager.GetString("tapudurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string tarih {
            get {
                return ResourceManager.GetString("tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşına Tavsiye Et.
        /// </summary>
        public static string tavsiyeet {
            get {
                return ResourceManager.GetString("tavsiyeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi D..
        /// </summary>
        public static string taxoffice {
            get {
                return ResourceManager.GetString("taxoffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portföy Tipi.
        /// </summary>
        public static string tip {
            get {
                return ResourceManager.GetString("tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Tipi.
        /// </summary>
        public static string tipemlak {
            get {
                return ResourceManager.GetString("tipemlak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portföy Tipi.
        /// </summary>
        public static string transactiontype {
            get {
                return ResourceManager.GetString("transactiontype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim.
        /// </summary>
        public static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizyonumuz.
        /// </summary>
        public static string vision {
            get {
                return ResourceManager.GetString("vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizyonumuz ve Misyonumuz.
        /// </summary>
        public static string visionmision {
            get {
                return ResourceManager.GetString("visionmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neden Biz?.
        /// </summary>
        public static string whyus {
            get {
                return ResourceManager.GetString("whyus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofis.
        /// </summary>
        public static string workplace {
            get {
                return ResourceManager.GetString("workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakıt Tipi.
        /// </summary>
        public static string yakittipi {
            get {
                return ResourceManager.GetString("yakittipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapının Durumu.
        /// </summary>
        public static string yapinindurumu {
            get {
                return ResourceManager.GetString("yapinindurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yok.
        /// </summary>
        public static string yok {
            get {
                return ResourceManager.GetString("yok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizin.
        /// </summary>
        public static string your {
            get {
                return ResourceManager.GetString("your", resourceCulture);
            }
        }
    }
}
